### ISSUE TITLE
更新环境变量问题

### ISSUE THREAD

**Issue by SugarCarry** [boris1993/qinglong-bot#4]
通过电报机器人发送更新环境变量，但是我需要修改的环境变量中含有=号。。所以导致更新不成功  更新环境变量#名称xxx=123=shxn     所以这种环境变量有没有解决方法  123=xxxx的变量。

**Comment by srlihg66** [comment]
没有的环境变量不能直接创建 有等号无法识别 
![85ee27aed8b25f6f78956f777669aab8](https://github.com/boris1993/qinglong-bot/assets/64582113/a201f830-a8cd-4846-a010-30c6a9d9704a)
![IMG_3182](https://github.com/boris1993/qinglong-bot/assets/64582113/cac3c53f-9119-443d-9987-80672a269219)

**Comment by boris1993** [comment]
@SugarCarry 问题知道了，我改天修掉
@srlihg66 我会再加个创建环境变量的命令
甲骨文机器上连不上Telegram感觉好怪……我回头试试

**Comment by SugarCarry** [comment]
> @SugarCarry 问题知道了，我改天修掉
> @srlihg66 我会再加个创建环境变量的命令
> 甲骨文机器上连不上Telegram感觉好怪……我回头试试

OK，麻烦大佬了。

**Comment by boris1993** [comment]
@srlihg66 
> Telegram机器人无法连接到Telegram服务器，初始化失败。错误信息：request to [https://api.telegram.org/bot7291507154:[REDACTED]/getMe](https://api.telegram.org/bot7291507154:%5BREDACTED%5D/getMe) failed, reason:

我在我的甲骨文大阪ARM和x86机器上都没法复现。系统是Ubuntu 22.04.4 LTS。

你执行下`curl -Lv  https://api.telegram.org/bot<BOT_TOKEN>/getMe`，看看输出是什么。

**Comment by srlihg66** [comment]
> @srlihg66
> 
> > Telegram机器人无法连接到Telegram服务器，初始化失败。错误信息：请求[https://api.telegram.org/bot7291507154:[REDACTED]/getMe](https://api.telegram.org/bot7291507154:%5BREDACTED%5D/getMe)失败，原因:
> 
> 我在大阪的甲骨文ARM和x86机器上还没有法律复现。系统是Ubuntu 22.04.4 LTS。
> 
> 你执行下`curl -Lv https://api.telegram.org/bot<BOT_TOKEN>/getMe`，看看输出是什么。

我ping和这个都正常的 都有东西  就是一运行报错这个 我是春川 我自己构建成18.2就正常了 之前跑了几十次一样的  我系统不是乌班图 我是rockyLinux 9.4

**Comment by boris1993** [comment]
> > @srlihg66
> > > Telegram机器人无法连接到Telegram服务器，初始化失败。错误信息：请求[https://api.telegram.org/bot7291507154:[REDACTED]/getMe](https://api.telegram.org/bot7291507154:%5BREDACTED%5D/getMe)失败，原因:
> > 
> > 
> > 我在大阪的甲骨文ARM和x86机器上还没有法律复现。系统是Ubuntu 22.04.4 LTS。
> > 你执行下`curl -Lv https://api.telegram.org/bot<BOT_TOKEN>/getMe`，看看输出是什么。
> 
> 我ping和这个都正常的 都有东西 就是一运行报错这个 我是春川 我自己构建成18.2就正常了 之前跑了几十次一样的 我系统不是乌班图 我是rockyLinux 9.4

行吧，我没有配额再建个RockyLinux的去测试了，回头我再打个node 18的镜像出来吧

**Comment by boris1993** [comment]
@srlihg66 你试试`node18-master`这个tag的镜像能不能用

**Comment by srlihg66** [comment]
> @srlihg66 你试试`node18-master`这个tag的镜像能不能用

这个镜像可以用 工作一切正常

**Comment by srlihg66** [comment]
> @srlihg66 你试试`node18-master`这个tag的镜像能不能用

我重启了一下网络 systemctl restart NetworkManager boris1993/qinglong-bot:latest 也可以了  很奇怪 还是网络上的问题

**Comment by boris1993** [comment]
@SugarCarry 在1.0.6修复了，重新拉latest就行

**Comment by boris1993** [comment]
> @SugarCarry 在1.0.6修复了，重新拉latest就行

1.0.7增加了`添加环境变量`功能

**Comment by SugarCarry** [comment]
> > @SugarCarry 在1.0.6修复了，重新拉latest就行
> 
> 1.0.7增加了`添加环境变量`功能

ok拉取完成，测试成功，感谢🙏🏻
