### ISSUE TITLE
希望增加功能

### ISSUE THREAD

**Issue by haile319** [boris1993/qinglong-bot#6]
安装试了一下，挺好用的，但是有多个ck的怎么更新其中一个，另外在获取所有变量时需要显示变量的备注，有些变量光看名称比较茫然

**Comment by boris1993** [comment]
> 有多个ck的怎么更新其中一个

可不可以给个示例？如果你是指`ck=key1;key2;key3`这种，而只想更新`key2`的话，这个我目前不打算支持。

> 在获取所有变量时需要显示变量的备注

我会加一个开关控制获取所有变量的时候会不会显示备注

**Comment by boris1993** [comment]
显示变量备注功能在提交`080841e`中完成。
