### ISSUE TITLE
环境变量更新失败 请求失败 Unauthorized Error

### ISSUE THREAD

**Issue by ImproveRei0** [boris1993/qinglong-bot#7]
青龙版本           2.10.13版
docker及容器   最新版

青龙api秘钥确认无误

描述：钉钉机器人更新环境变量或添加环境变量提示  **“请求失败 Unauthorized Error”**

另：似乎**所有指令**都会返回 **“请求失败 Unauthorized Error”**，但是_搭建完成之后试验前几次没问题_

**Comment by boris1993** [comment]
可能是因为接口不兼容。我开发机器人用的青龙面板应该没这么老，刚刚用2.10.13测试的时候发现它API字段和内容跟机器人现在兼容的版本不一样。如果你能提供一个详细的复现步骤的话，就能帮我更好的确定是接口兼容性问题还是代码的问题。
目前我测出来的是，获取所有环境变量和新增环境变量没问题，更新环境变量因为ID字段变了所以失败。
所以目前没有好的解决方案，要么升级青龙面板，要么你fork出来一份做适配。
我抽空也会看看青龙在哪个版本做的API改动，并试着做下兼容性适配。

**Comment by boris1993** [comment]
不是，哥们，还在用2021年的版本啊？能更新就更新了吧，我不太想花时间兼容一个上古时代的宝贝……

**Comment by ImproveRei0** [comment]
哈哈辛苦了老哥，谢谢提醒。
可能是太稳定了所以没注意到版本已经这么古老了，有空把他更新了。
我初步发现问题是这样的：
创建应用之后如果**改动该应用的权限**，那么即使**Client ID | Client Secret不会发生变化**
那么也会导致这个应用失效
解决办法就是**生成之后不要改动权限**
当然仅限  2.10.13版 ，还是用新的版本比较好

**Comment by boris1993** [comment]
感谢反馈问题的原因！
